package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;

public class LoginViewController {
	@FXML
	private Button Btn_log;
	@FXML
	private TextField lgn_ID;
	@FXML
	private PasswordField lgn_PW;
	@FXML
	private Button Btn_reg;

	ObservableList<TableModel> oblist = FXCollections.observableArrayList();

	// Event Listener on Button.onAction
	@FXML
	public void lgn_Clicked(ActionEvent event) {
		// TODO Autogenerated
		String PWfromDB = members_load(lgn_ID.getText());
		
		try {
			if(PWfromDB.equals(lgn_PW.getText())&&PWfromDB!="") {
				JOptionPane.showMessageDialog(null, "로그인 성공");
				Stage loginStage = (Stage) Btn_reg.getScene().getWindow();
				Stage registStage = new Stage();
				Parent root;
				root = FXMLLoader.load(getClass().getResource("MainView.fxml"));

				Scene scene = new Scene(root);

				registStage.setTitle("회원가입");
				registStage.setScene(scene);
				registStage.show();

				loginStage.close();
			}
			else {
				JOptionPane.showMessageDialog(null, "로그인 실패");
			}
		} catch(Exception e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button.onAction
	@FXML
	public void reg_Clicked(ActionEvent event) {
		// TODO Autogenerated
		Stage loginStage = (Stage) Btn_reg.getScene().getWindow();
		Stage registStage = new Stage();
		Parent root;

		try {

			root = FXMLLoader.load(getClass().getResource("MainView.fxml"));

			Scene scene = new Scene(root);

			registStage.setTitle("회원가입");
			registStage.setScene(scene);
			registStage.show();

			loginStage.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public static String members_load(String id) {
		Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;
		
		String pw = "";
		
		try {
			conn = DBConnection.getConnection();
			stmt = conn.createStatement();
			
			String sql = "SELECT pw FROM TEST1 WHERE id = "+"'"+id+"'";
			rs = stmt.executeQuery(sql);
			
			while(rs.next()) {
				pw = rs.getString(1);
			}
			
		} catch(Exception e) {
			e.printStackTrace();
		}
		finally {
			try {
				if(conn != null && !conn.isClosed()) {
					conn.close();
				}
				if(stmt != null && stmt.isClosed()) {
					stmt.close();
				}
			} catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pw;
	}
}
