package application;

import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.PasswordField;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class MainViewController implements Initializable {
	@FXML
	private TableView<TableModel> tAble;
	@FXML
	private TableColumn<TableModel, String> rID;
	@FXML
	private TableColumn<TableModel, String> rPW;
	@FXML
	private TableColumn<TableModel, String> rPH;
	@FXML
	private TextField ipID;
	@FXML
	private TextField ipPH;
	@FXML
	private PasswordField ipPW;

	ObservableList<TableModel> oblist = FXCollections.observableArrayList();

	// Event Listener on Button.onAction
	@FXML
	public void getRegister(ActionEvent event) {
		// TODO Autogenerated

		try {
			Connection conn = DBConnection.getConnection();
			String sql = "INSERT INTO TEST1 (id,pw,phone) VALUES(";

			sql = sql + "'" + ipID.getText() + "','" + ipPW.getText() + "','" + ipPH.getText() + "')";
			conn.createStatement().executeQuery(sql);

			JOptionPane.showMessageDialog(null, "Users Add Success");

			TableModel tmp;
			tmp = new TableModel(ipID.getText(), ipPW.getText(), ipPH.getText());
			oblist.add(tmp);
			tAble.setItems(oblist);
			conn.close();

		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e);
		}

	}

	public void del_Clicked(ActionEvent ae) throws SQLException {

		Connection conn = DBConnection.getConnection();

		TableModel selected = tAble.getSelectionModel().getSelectedItem();

		String sql = "DELETE FROM TEST1 WHERE id ='";

		sql = sql + selected.getId()+"'";

		conn.createStatement().executeQuery(sql);

		oblist.remove(selected);
		
		JOptionPane.showMessageDialog(null, "Users Delete Success");

		tAble.setItems(oblist);

		conn.close();
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {

		Connection conn = DBConnection.getConnection();
		try {
			ResultSet rs = conn.createStatement().executeQuery("select * from TEST1");
			while (rs.next()) {
				oblist.add(new TableModel(rs.getString("id"), rs.getString("pw"), rs.getString("phone")));
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		rID.setCellValueFactory(new PropertyValueFactory<>("id"));
		rPW.setCellValueFactory(new PropertyValueFactory<>("pw"));
		rPH.setCellValueFactory(new PropertyValueFactory<>("phone"));

		tAble.setItems(oblist);
	}
}
